# Generated by Django 4.2.5 on 2024-01-26 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Компания')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('password_app', models.CharField(blank=True, max_length=500, null=True, verbose_name='Пароль приложения')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': '1 Компании',
            },
        ),
        migrations.CreateModel(
            name='HistoricalHuman',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('groups', models.CharField(db_index=True, max_length=300, null=True)),
                ('first_name', models.CharField(db_index=True, default='', max_length=200, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, default='', max_length=200, null=True, verbose_name='Фамилия')),
                ('sur_name', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Отчество')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Начало работы')),
                ('comment_update', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('comment', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Комментарий')),
                ('time_update', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата обновления')),
                ('employee_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер сотрудника в базе данных кадровой службы')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author_update', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user_update')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'historical 3 Люди',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.CharField(db_index=True, max_length=300, null=True)),
                ('first_name', models.CharField(db_index=True, default='', max_length=200, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, default='', max_length=200, null=True, verbose_name='Фамилия')),
                ('sur_name', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Отчество')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Начало работы')),
                ('comment_update', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('comment', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Комментарий')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('employee_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер сотрудника в базе данных кадровой службы')),
                ('author_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humans', to=settings.AUTH_USER_MODEL, verbose_name='user_update')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': '3 Люди',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('import_name', models.CharField(max_length=255, verbose_name='Экспорт View')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='imports/input_file/', verbose_name='Входной файл')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='imports/output_file/', verbose_name='Выходной файл')),
                ('output_file_to_admin', models.FileField(blank=True, null=True, upload_to='imports/output_file/', verbose_name='Выходной файл для администратора')),
                ('is_edit', models.BooleanField(default=True, verbose_name='Можно редактировать')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='ImportExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='imports/example/', verbose_name='Шаблон')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Подразделение')),
                ('сompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='table.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': '1 Подразделения',
                'ordering': ['title'],
                'unique_together': {('сompany', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Должность')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='table.office', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': '2 Должности',
                'ordering': ['title'],
                'unique_together': {('office', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_code', models.CharField(max_length=10, verbose_name='Цифровой код')),
                ('character_code', models.CharField(max_length=10, verbose_name='Сивольный код')),
                ('title', models.CharField(max_length=150, verbose_name='Расшифровка')),
            ],
            options={
                'verbose_name': 'Причина пропуска',
                'verbose_name_plural': '5 Причины пропуска',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': '6 Смены',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус работника',
                'verbose_name_plural': '5 Статусы работника',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleNotJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Примечание')),
                ('length_time', models.IntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_snj', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_snj', to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snj', to='table.human', verbose_name='Сотрудник')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snj', to='table.office', verbose_name='Подразделение')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snj', to='table.post', verbose_name='Должность')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snj', to='table.reason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Данные пропуска',
                'verbose_name_plural': '7 Данные пропусков',
            },
        ),
        migrations.CreateModel(
            name='ImportSNJStatusField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file_modify', models.TextField(blank=True, null=True, verbose_name='Переходный файл')),
                ('input_file_modify_original', models.TextField(blank=True, null=True, verbose_name='Переходный исходный файл')),
                ('office', models.BooleanField(default=False, verbose_name='Подразделения')),
                ('post', models.BooleanField(default=False, verbose_name='Должности')),
                ('fio', models.BooleanField(default=False, verbose_name='ФИО')),
                ('reason', models.BooleanField(default=False, verbose_name='Причина пропуска')),
                ('shift', models.BooleanField(default=False, verbose_name='Смена')),
                ('date', models.BooleanField(default=False, verbose_name='Даты')),
                ('comment', models.BooleanField(default=False, verbose_name='Комментарии')),
                ('import_parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='table.import', verbose_name='Импорт')),
            ],
        ),
        migrations.AddField(
            model_name='human',
            name='office',
            field=models.ManyToManyField(related_name='humans', to='table.office', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='human',
            name='post',
            field=models.ManyToManyField(related_name='humans', to='table.post', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='human',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humans', to='table.shift', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='human',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.workstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='human',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humans_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='HistoricalScheduleNotJob',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Примечание')),
                ('length_time', models.IntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('editor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='snj', to='table.schedulenotjob')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('human', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='table.human', verbose_name='Сотрудник')),
                ('office', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='table.office', verbose_name='Подразделение')),
                ('post', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='table.post', verbose_name='Должность')),
                ('reason', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='table.reason', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'historical 7 Данные пропусков',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHuman_post',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='table.historicalhuman')),
                ('human', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='table.human')),
                ('post', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='table.post')),
            ],
            options={
                'verbose_name': 'HistoricalHuman_post',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalhuman',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='humans', to='table.human'),
        ),
        migrations.AddField(
            model_name='historicalhuman',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhuman',
            name='shift',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='table.shift', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='historicalhuman',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='table.workstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='historicalhuman',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='ShiftOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start_date', models.DateTimeField(null=True, verbose_name='Дата начала цикла')),
                ('cycle_end_date', models.DateTimeField(null=True, verbose_name='Дата окончания цикла')),
                ('work_days_hours', models.JSONField(null=True, verbose_name='Рабочие дни и часы')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.office', verbose_name='Подразделение')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Смена в подразделении',
                'verbose_name_plural': 'Смены в подразделениях',
                'unique_together': {('office', 'shift')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='human',
            unique_together={('user', 'employee_number')},
        ),
    ]
