# Generated by Django 4.2.5 on 2024-01-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_historicalschedulenotjob_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='digital_code',
        ),
        migrations.AddField(
            model_name='reason',
            name='body',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Продукт'),
        ),
    ]
